apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.container.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: web-server
